# Conda Environment Setup Instructions
#  - Using an environment.yml file with conda
#  - Key Terminal Commands:
#    
#    conda deactivate (preparation for installation)
#    conda env create -f environment.yml
#    conda env update --file environment.yml --prune
#
#    conda env export --name stock > environment.yml
#    conda env remove --name stock
#    conda env list

name: stock
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python==3.11
  - anyio==4.3.0
  - appdirs==1.4.4
  - asgiref==3.8.1
  - attrs==23.2.0
  - backcall==0.2.0
  - beautifulsoup4==4.12.3
  - certifi==2024.2.2
  - charset-normalizer==3.3.2
  - click==8.1.7
  - cmdstanpy==1.2.2
  - contourpy==1.2.1
  - cycler==0.12.1
  - fonttools==4.50.0
  - frozendict==2.4.0
  - h11==0.14.0
  - holidays==0.46
  - html5lib==1.1
  - htmltools==0.5.1
  - idna==3.6
  - importlib_resources==6.4.0
  - ipython==8.12.2
  - ipywidgets==8.1.2
  - Jinja2==3.1.3
  - jsonschema==4.21.1
  - jsonschema-specifications==2023.12.1
  - jupyter_client==8.3.0
  - jupyter_core==5.3.2
  - jupyterlab_widgets==3.0.10
  - kiwisolver==1.4.5
  - linkify-it-py==2.0.3
  - lxml==5.1.0
  - markdown-it-py==3.0.0
  - MarkupSafe==2.1.5
  - matplotlib==3.8.4
  - mdit-py-plugins==0.4.0
  - nbformat==5.10.3
  - numpy==1.26.4
  - packaging==23.2
  - pandas==2.2.1
  - pandas-datareader==0.10.0
  - peewee==3.17.1
  - pillow==10.3.0
  - prompt-toolkit==3.0.36
  - Pygments==2.16.1
  - PyJWT==2.8.0
  - pyparsing==3.1.2
  - python-multipart==0.0.9
  - pytz==2024.1
  - questionary==2.0.1
  - referencing==0.34.0
  - requests==2.31.0
  - rpds-py==0.18.0
  - semver==2.13.0
  - shiny==0.8.1
  - sniffio==1.3.1
  - soupsieve==2.5
  - stanio==0.5.0
  - starlette==0.37.2
  - tenacity==8.2.3
  - tqdm==4.66.2
  - uc-micro-py==1.0.3
  - urllib3==2.2.1
  - uvicorn==0.29.0
  - watchfiles==0.21.0
  - websockets==12.0
  - widgetsnbextension==4.0.10
  - yfinance==0.2.37
  - pip
  - pip:
      - appnope
      - asttokens
      - comm
      - debugpy
      - decorator
      - exceptiongroup
      - executing
      - importlib_metadata
      - jedi
      - matplotlib-inline
      - nest_asyncio
      - parso
      - pexpect
      - pickleshare
      - platformdirs
      - psutil
      - ptyprocess
      - pure-eval
      - python-dateutil
      - pyzmq
      - six
      - stack-data
      - tornado
      - traitlets
      - typing_extensions
      - wcwidth
      - zipp
      - tzdata==2024.1
      - shinywidgets==0.3.1
      - shinyswatch==0.5.1
      - rsconnect_python==1.22.0
      - prophet==1.1.5
      - plotly==5.20.0
      - multitasking==0.0.11
      - ipykernel
      - fastjsonschema==2.19.1
      - faicons==0.2.2